# Black
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      .eggs         
    | .git         
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

# iSort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
virtual_env = "myenv"

# Pytest
[tool.pytest.ini_options]

# Pytest coverage
[tool.coverage.run]